#!/usr/bin/env python3
"""Run an external-aero OpenFOAM case (snappyHexMesh + simpleFoam, k-omega SST)
around body.stl and upload the results.

Cloud mode (AWS Batch): env JOB_ID, BUCKET, PARAMS (JSON). Reads
s3://BUCKET/inputs/JOB_ID/body.stl, writes s3://BUCKET/outputs/JOB_ID/.

Local mode:  run_foam.py --local body.stl --out results/ --params '{"speed":30}'

STL convention (what Splat Tunnel exports): meters, x = downstream, y = up.
PARAMS: speed (m/s), fluid ("air"|"water"), ground (bool), frontalArea (m^2),
        length (m), baseCells (cells along the body at level 0, default 16),
        iterations (default 1500), quality ("draft"|"standard"|"fine").
"""
import argparse, json, math, os, shutil, struct, subprocess, sys, time, zipfile

FLUIDS = {"air": {"rho": 1.204, "nu": 1.51e-5}, "water": {"rho": 998.0, "nu": 1.0e-6}}
QUALITY = {"draft": (12, (2, 3), 1), "standard": (16, (3, 4), 2), "fine": (20, (4, 5), 2)}


def log(*a):
    print(time.strftime("%H:%M:%S"), *a, flush=True)


# ---------------------------------------------------------------- STL
def read_stl(path):
    data = open(path, "rb").read()
    tris = []
    if len(data) >= 84 and 84 + 50 * struct.unpack_from("<I", data, 80)[0] == len(data):
        n = struct.unpack_from("<I", data, 80)[0]
        for t in range(n):
            v = struct.unpack_from("<9f", data, 84 + 50 * t + 12)
            tris.append(v)
    else:
        vals = []
        for line in data.decode("utf-8", "ignore").splitlines():
            s = line.split()
            if len(s) == 4 and s[0] == "vertex":
                vals += [float(x) for x in s[1:]]
        tris = [vals[i:i + 9] for i in range(0, len(vals), 9)]
    if not tris:
        raise SystemExit("body.stl has no triangles")
    lo = [min(t[k + 3 * j] for t in tris for j in range(3)) for k in range(3)]
    hi = [max(t[k + 3 * j] for t in tris for j in range(3)) for k in range(3)]
    return tris, lo, hi


def write_ascii_stl(path, tris, name="body"):
    # snappy names the patch after the solid name, so write it explicitly
    with open(path, "w") as f:
        f.write(f"solid {name}\n")
        for t in tris:
            ax, ay, az, bx, by, bz, cx, cy, cz = t
            ux, uy, uz, vx, vy, vz = bx - ax, by - ay, bz - az, cx - ax, cy - ay, cz - az
            nx, ny, nz = uy * vz - uz * vy, uz * vx - ux * vz, ux * vy - uy * vx
            l = math.sqrt(nx * nx + ny * ny + nz * nz) or 1.0
            f.write(f" facet normal {nx/l:.6e} {ny/l:.6e} {nz/l:.6e}\n  outer loop\n")
            for j in range(3):
                f.write(f"   vertex {t[3*j]:.7e} {t[3*j+1]:.7e} {t[3*j+2]:.7e}\n")
            f.write("  endloop\n endfacet\n")
        f.write(f"endsolid {name}\n")


# ---------------------------------------------------------------- case files
HEADER = """/*--------------------------------*- C++ -*----------------------------------*\\
  Generated by Splat Tunnel
\\*---------------------------------------------------------------------------*/
FoamFile
{{
    version     2.0;
    format      ascii;
    class       {cls};
    object      {obj};
}}
"""


def foam(path, cls, obj, body):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(HEADER.format(cls=cls, obj=obj) + body)


def v(x):
    return f"({x[0]:.6g} {x[1]:.6g} {x[2]:.6g})"


def build_case(case, stl_path, p):
    tris, lo, hi = read_stl(stl_path)
    size = [hi[k] - lo[k] for k in range(3)]
    L = max(size)
    ground = bool(p.get("ground", True))
    fluid = FLUIDS.get(p.get("fluid", "air"), FLUIDS["air"])
    U = float(p.get("speed", 30.0))
    base_cells, (smin, smax), wake_level = QUALITY.get(p.get("quality", "standard"), QUALITY["standard"])
    base_cells = int(p.get("baseCells", base_cells))
    iters = int(p.get("iterations", 1500))
    lx, hy, wz = size
    d = max(hy, wz, 1e-6)
    up, down = max(0.8 * lx, 2 * d), max(2 * lx, 5 * d)
    x0, x1 = lo[0] - up, hi[0] + down
    if ground:
        y0 = lo[1] + 0.005 * L  # sink the body slightly into the ground: clean contact patch
        y1 = y0 + max(hy * 4.5, wz * 2)
    else:
        cy = (lo[1] + hi[1]) / 2
        half = max(hy * 5, wz * 3) / 2
        y0, y1 = cy - half, cy + half
    cz = (lo[2] + hi[2]) / 2
    halfz = max(wz * 5, hy * 3) / 2
    z0, z1 = cz - halfz, cz + halfz
    h = L / base_cells
    n = [max(4, math.ceil((x1 - x0) / h)), max(4, math.ceil((y1 - y0) / h)), max(4, math.ceil((z1 - z0) / h))]
    area = float(p.get("frontalArea") or 0) or max(hy * wz * 0.8, 1e-9)
    log(f"body {size[0]:.3f} x {size[1]:.3f} x {size[2]:.3f} m, domain cells {n}, base h {h:.4f} m, U {U} m/s")

    os.makedirs(os.path.join(case, "constant", "triSurface"), exist_ok=True)
    write_ascii_stl(os.path.join(case, "constant", "triSurface", "body.stl"), tris)
    open(os.path.join(case, "case.foam"), "w").close()  # ParaView opens this

    foam(f"{case}/system/blockMeshDict", "dictionary", "blockMeshDict", f"""
scale 1;
vertices
(
    ({x0:.6g} {y0:.6g} {z0:.6g}) ({x1:.6g} {y0:.6g} {z0:.6g}) ({x1:.6g} {y1:.6g} {z0:.6g}) ({x0:.6g} {y1:.6g} {z0:.6g})
    ({x0:.6g} {y0:.6g} {z1:.6g}) ({x1:.6g} {y0:.6g} {z1:.6g}) ({x1:.6g} {y1:.6g} {z1:.6g}) ({x0:.6g} {y1:.6g} {z1:.6g})
);
blocks ( hex (0 1 2 3 4 5 6 7) ({n[0]} {n[1]} {n[2]}) simpleGrading (1 1 1) );
boundary
(
    inlet  {{ type patch; faces ((0 4 7 3)); }}
    outlet {{ type patch; faces ((1 2 6 5)); }}
    ground {{ type wall;  faces ((0 1 5 4)); }}
    top    {{ type patch; faces ((3 7 6 2)); }}
    sides  {{ type patch; faces ((0 3 2 1) (4 5 6 7)); }}
);
""")
    foam(f"{case}/system/surfaceFeatureExtractDict", "dictionary", "surfaceFeatureExtractDict", """
body.stl
{
    extractionMethod    extractFromSurface;
    extractFromSurfaceCoeffs { includedAngle 150; }
    writeObj            no;
}
""")
    # wake refinement box: body plus 1.5 lengths downstream
    wlo = [lo[0] - 0.1 * L, max(y0, lo[1] - 0.2 * hy), lo[2] - 0.2 * wz]
    whi = [hi[0] + 1.5 * L, hi[1] + 0.4 * hy, hi[2] + 0.2 * wz]
    # a seed point in the fluid: just downstream of the inlet, off any cell face
    loc = [x0 + 0.37 * h + 0.5 * up * 0.3, y1 - 0.61 * h, z0 + 0.53 * h + 0.13 * (z1 - z0)]
    foam(f"{case}/system/snappyHexMeshDict", "dictionary", "snappyHexMeshDict", f"""
castellatedMesh true;
snap            true;
addLayers       false;
geometry
{{
    body.stl {{ type triSurfaceMesh; name body; }}
    wake {{ type searchableBox; min {v(wlo)}; max {v(whi)}; }}
}}
castellatedMeshControls
{{
    maxLocalCells 4000000;
    maxGlobalCells 12000000;
    minRefinementCells 10;
    maxLoadUnbalance 0.10;
    nCellsBetweenLevels 3;
    features ( {{ file "body.eMesh"; level {smax}; }} );
    refinementSurfaces {{ body {{ level ({smin} {smax}); patchInfo {{ type wall; }} }} }}
    resolveFeatureAngle 30;
    refinementRegions {{ wake {{ mode inside; levels ((1E15 {wake_level})); }} }}
    locationInMesh {v(loc)};
    allowFreeStandingZoneFaces true;
}}
snapControls
{{
    nSmoothPatch 3;
    tolerance 2.0;
    nSolveIter 50;
    nRelaxIter 5;
    nFeatureSnapIter 10;
    implicitFeatureSnap false;
    explicitFeatureSnap true;
    multiRegionFeatureSnap false;
}}
addLayersControls
{{
    relativeSizes true;
    layers {{ }}
    expansionRatio 1.2;
    finalLayerThickness 0.5;
    minThickness 0.1;
    nGrow 0;
    featureAngle 60;
    nRelaxIter 3;
    nSmoothSurfaceNormals 1;
    nSmoothNormals 3;
    nSmoothThickness 10;
    maxFaceThicknessRatio 0.5;
    maxThicknessToMedialRatio 0.3;
    minMedialAxisAngle 90;
    nBufferCellsNoExtrude 0;
    nLayerIter 50;
}}
meshQualityControls
{{
    maxNonOrtho 65;
    maxBoundarySkewness 20;
    maxInternalSkewness 4;
    maxConcave 80;
    minVol 1e-13;
    minTetQuality 1e-15;
    minArea -1;
    minTwist 0.02;
    minDeterminant 0.001;
    minFaceWeight 0.05;
    minVolRatio 0.01;
    minTriangleTwist -1;
    nSmoothScale 4;
    errorReduction 0.75;
}}
mergeTolerance 1e-6;
""")
    nproc = int(p.get("nproc") or os.cpu_count() or 1)
    foam(f"{case}/system/decomposeParDict", "dictionary", "decomposeParDict", f"""
numberOfSubdomains {nproc};
method scotch;
""")
    cofr = [(lo[k] + hi[k]) / 2 for k in range(3)]
    foam(f"{case}/system/controlDict", "dictionary", "controlDict", f"""
application     simpleFoam;
startFrom       latestTime;
startTime       0;
stopAt          endTime;
endTime         {iters};
deltaT          1;
writeControl    timeStep;
writeInterval   {iters};
purgeWrite      1;
writeFormat     binary;
writePrecision  8;
timeFormat      general;
timePrecision   6;
runTimeModifiable false;
{"functions" if p.get("functions", True) else "disabledFunctions"}
{{
    forceCoeffs
    {{
        type            forceCoeffs;
        libs            ("libforces.so");
        writeControl    timeStep;
        writeInterval   1;
        patches         (body);
        rho             rhoInf;
        rhoInf          {fluid['rho']};
        CofR            {v(cofr)};
        liftDir         (0 1 0);
        dragDir         (1 0 0);
        pitchAxis       (0 0 1);
        magUInf         {U};
        lRef            {L:.6g};
        Aref            {area:.6g};
    }}
    slices
    {{
        type            surfaces;
        libs            ("libsampling.so");
        writeControl    writeTime;
        surfaceFormat   vtk;
        fields          (p U);
        interpolationScheme cellPoint;
        surfaces
        {{
            midPlane   {{ type cuttingPlane; planeType pointAndNormal; pointAndNormalDict {{ point {v([cofr[0], cofr[1], cz])}; normal (0 0 1); }} interpolate true; }}
            bodySurface {{ type patch; patches (body); interpolate true; }}
        }}
    }}
}}
""")
    foam(f"{case}/system/fvSchemes", "dictionary", "fvSchemes", """
ddtSchemes { default steadyState; }
gradSchemes { default Gauss linear; grad(U) cellLimited Gauss linear 1; grad(k) cellLimited Gauss linear 1; grad(omega) cellLimited Gauss linear 1; }
divSchemes
{
    default none;
    div(phi,U) bounded Gauss linearUpwindV grad(U);
    div(phi,k) bounded Gauss upwind;
    div(phi,omega) bounded Gauss upwind;
    div((nuEff*dev2(T(grad(U))))) Gauss linear;
}
laplacianSchemes { default Gauss linear limited corrected 0.33; }
interpolationSchemes { default linear; }
snGradSchemes { default limited corrected 0.33; }
wallDist { method meshWave; }
""")
    foam(f"{case}/system/fvSolution", "dictionary", "fvSolution", """
solvers
{
    p { solver GAMG; tolerance 1e-7; relTol 0.01; smoother GaussSeidel; }
    Phi { $p; }
    U { solver smoothSolver; smoother GaussSeidel; tolerance 1e-8; relTol 0.1; nSweeps 1; }
    k { $U; }
    omega { $U; }
}
SIMPLE { nNonOrthogonalCorrectors 0; consistent yes; }
potentialFlow { nNonOrthogonalCorrectors 5; }
relaxationFactors { equations { U 0.9; k 0.7; omega 0.7; } }
cache { grad(U); }
""")
    foam(f"{case}/constant/transportProperties", "dictionary", "transportProperties", f"""
transportModel  Newtonian;
nu              {fluid['nu']};
""")
    # "RASModel" for older openfoam.com releases, "model" for v2006+
    foam(f"{case}/constant/turbulenceProperties", "dictionary", "turbulenceProperties", """
simulationType RAS;
RAS { RASModel kOmegaSST; model kOmegaSST; turbulence on; printCoeffs on; }
""")
    # freestream turbulence: 0.5% intensity, length scale 5% of body
    k = 1.5 * (0.005 * U) ** 2
    omega = math.sqrt(k) / (0.09 ** 0.25 * 0.05 * L)
    ground_U = f"type fixedValue; value uniform ({U} 0 0);" if ground else "type slip;"
    ground_wf = "type kqRWallFunction; value $internalField;" if ground else "type slip;"
    ground_om = "type omegaWallFunction; value $internalField;" if ground else "type slip;"
    ground_nut = "type nutkWallFunction; value uniform 0;" if ground else "type calculated; value uniform 0;"
    far = "top { type slip; } sides { type slip; }"
    foam(f"{case}/0/U", "volVectorField", "U", f"""
dimensions [0 1 -1 0 0 0 0];
internalField uniform ({U} 0 0);
boundaryField
{{
    #includeEtc "caseDicts/setConstraintTypes"
    inlet {{ type fixedValue; value uniform ({U} 0 0); }}
    outlet {{ type inletOutlet; inletValue uniform (0 0 0); value $internalField; }}
    ground {{ {ground_U} }}
    body {{ type noSlip; }}
    {far}
}}
""")
    foam(f"{case}/0/p", "volScalarField", "p", """
dimensions [0 2 -2 0 0 0 0];
internalField uniform 0;
boundaryField
{
    #includeEtc "caseDicts/setConstraintTypes"
    inlet { type zeroGradient; }
    outlet { type fixedValue; value uniform 0; }
    ground { type zeroGradient; }
    body { type zeroGradient; }
    top { type slip; } sides { type slip; }
}
""")
    for name, val, wall in (("k", k, "type kqRWallFunction; value $internalField;"), ("omega", omega, "type omegaWallFunction; value $internalField;")):
        g = ground_wf if name == "k" else ground_om
        dims = "[0 2 -2 0 0 0 0]" if name == "k" else "[0 0 -1 0 0 0 0]"
        foam(f"{case}/0/{name}", "volScalarField", name, f"""
dimensions {dims};
internalField uniform {val:.6g};
boundaryField
{{
    #includeEtc "caseDicts/setConstraintTypes"
    inlet {{ type fixedValue; value $internalField; }}
    outlet {{ type inletOutlet; inletValue $internalField; value $internalField; }}
    ground {{ {g} }}
    body {{ {wall} }}
    {far}
}}
""")
    foam(f"{case}/0/nut", "volScalarField", "nut", f"""
dimensions [0 2 -1 0 0 0 0];
internalField uniform 0;
boundaryField
{{
    #includeEtc "caseDicts/setConstraintTypes"
    inlet {{ type calculated; value uniform 0; }}
    outlet {{ type calculated; value uniform 0; }}
    ground {{ {ground_nut} }}
    body {{ type nutkWallFunction; value uniform 0; }}
    top {{ type calculated; value uniform 0; }} sides {{ type calculated; value uniform 0; }}
}}
""")
    return {"U": U, "L": L, "area": area, "nproc": nproc, "iters": iters, "rho": fluid["rho"], "nu": fluid["nu"], "ground": ground, "base_cells": n}


# ---------------------------------------------------------------- running
def sh(cmd, case, logname):
    log("$", cmd)
    with open(os.path.join(case, f"log.{logname}"), "w") as f:
        r = subprocess.run(["bash", "-lc", f"{FOAM_SOURCE} cd '{case}' && {cmd}"], stdout=f, stderr=subprocess.STDOUT)
    if r.returncode != 0:
        tail = open(os.path.join(case, f"log.{logname}")).read()[-3000:]
        raise RuntimeError(f"{logname} failed:\n{tail}")


def find_bashrc():
    for base in ("/usr/lib/openfoam", "/opt", "/usr/share/openfoam"):
        if not os.path.isdir(base):
            continue
        cands = []
        for root, dirs, files in os.walk(base):
            if root.count(os.sep) - base.count(os.sep) > 2:
                dirs[:] = []
                continue
            if root.endswith("/etc") and "bashrc" in files:
                cands.append(os.path.join(root, "bashrc"))
        if cands:
            return sorted(cands)[-1]
    return None


BASHRC = os.environ.get("FOAM_BASHRC") or find_bashrc()
FOAM_SOURCE = f"source '{BASHRC}' >/dev/null 2>&1 || true;" if BASHRC else ""
MPI = "mpirun --allow-run-as-root --oversubscribe -np {n}"


def run_case(case, info):
    n = info["nproc"]
    os.environ.setdefault("OMPI_ALLOW_RUN_AS_ROOT", "1")
    os.environ.setdefault("OMPI_ALLOW_RUN_AS_ROOT_CONFIRM", "1")
    sh("blockMesh", case, "blockMesh")
    sh("surfaceFeatureExtract", case, "surfaceFeatureExtract")
    if n > 1:
        try:
            sh("decomposePar -force", case, "decomposePar")
        except RuntimeError as e:
            if "scotch" not in str(e):
                raise
            # some OpenFOAM builds ship without Scotch: split along x instead
            log("scotch unavailable, using hierarchical decomposition")
            foam(f"{case}/system/decomposeParDict", "dictionary", "decomposeParDict", f"""
numberOfSubdomains {n};
method hierarchical;
coeffs {{ n ({n} 1 1); order xyz; }}
hierarchicalCoeffs {{ n ({n} 1 1); delta 0.001; order xyz; }}
""")
            sh("decomposePar -force", case, "decomposePar")
        sh(f"{MPI.format(n=n)} snappyHexMesh -parallel -overwrite", case, "snappyHexMesh")
        sh(f"{MPI.format(n=n)} checkMesh -parallel", case, "checkMesh")
        # snappy leaves 0/ untouched in processor dirs; copy the initial fields in
        for i in range(n):
            pdir = os.path.join(case, f"processor{i}", "0")
            shutil.rmtree(pdir, ignore_errors=True)
            shutil.copytree(os.path.join(case, "0"), pdir)
        sh(f"{MPI.format(n=n)} potentialFoam -parallel -writephi", case, "potentialFoam")
        sh(f"{MPI.format(n=n)} simpleFoam -parallel", case, "simpleFoam")
        sh("reconstructParMesh -constant", case, "reconstructParMesh")
        sh("reconstructPar -latestTime", case, "reconstructPar")
        for i in range(n):
            shutil.rmtree(os.path.join(case, f"processor{i}"), ignore_errors=True)
    else:
        sh("snappyHexMesh -overwrite", case, "snappyHexMesh")
        sh("checkMesh", case, "checkMesh")
        sh("potentialFoam -writephi", case, "potentialFoam")
        sh("simpleFoam", case, "simpleFoam")


def collect(case, info, out):
    os.makedirs(out, exist_ok=True)
    rows = []
    for root, _, files in os.walk(os.path.join(case, "postProcessing", "forceCoeffs")):
        for fn in files:
            if fn.startswith("coefficient") or fn.startswith("forceCoeffs"):
                for line in open(os.path.join(root, fn)):
                    if line.startswith("#"):
                        hdr = line[1:].split()
                        continue
                    vals = line.split()
                    if vals:
                        rows.append(dict(zip(hdr, vals)))
    rows.sort(key=lambda r: float(r.get("Time", 0)))
    with open(os.path.join(out, "forces.csv"), "w") as f:
        f.write("iteration,cd,cl,cs\n")
        for r in rows:
            f.write(f"{r.get('Time')},{r.get('Cd')},{r.get('Cl')},{r.get('Cs', '')}\n")
    tail = rows[int(len(rows) * 0.8):] or rows
    avg = lambda k: sum(float(r[k]) for r in tail if k in r) / max(1, len(tail))
    cd, cl = (avg("Cd"), avg("Cl")) if tail else (None, None)
    drag = 0.5 * info["rho"] * info["U"] ** 2 * cd * info["area"] if cd is not None else None
    ncells = None
    try:
        for line in open(os.path.join(case, "log.checkMesh")):
            if line.strip().startswith("cells:"):
                ncells = int(line.split()[1])
    except OSError:
        pass
    summary = {
        "solver": "OpenFOAM simpleFoam, k-omega SST, snappyHexMesh (no boundary layers)",
        "speed_mps": info["U"], "reference_length_m": info["L"], "reference_area_m2": info["area"],
        "reynolds": info["U"] * info["L"] / info["nu"], "cells": ncells, "iterations": info["iters"],
        "cd": cd, "cl": cl, "drag_N": drag,
        "note": "Averaged over the last 20% of iterations. No prism layers, so skin friction is approximate; pressure drag dominates for bluff bodies.",
    }
    json.dump(summary, open(os.path.join(out, "summary.json"), "w"), indent=2)
    zpath = os.path.join(out, "openfoam_case.zip")
    with zipfile.ZipFile(zpath, "w", zipfile.ZIP_DEFLATED) as z:
        for root, dirs, files in os.walk(case):
            dirs[:] = [d for d in dirs if not d.startswith("processor")]
            for fn in files:
                full = os.path.join(root, fn)
                z.write(full, os.path.relpath(full, os.path.dirname(case)))
    log("summary", json.dumps(summary))
    return summary


# ---------------------------------------------------------------- entry
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--local", help="path to body.stl (skip S3)")
    ap.add_argument("--out", default="results")
    ap.add_argument("--params", default=None)
    ap.add_argument("--work", default="/tmp/job")
    a = ap.parse_args()
    params = json.loads(a.params or os.environ.get("PARAMS") or "{}")
    shutil.rmtree(a.work, ignore_errors=True)
    case = os.path.join(a.work, "case")
    os.makedirs(case)
    s3 = None
    if a.local:
        stl = a.local
        out = a.out
    else:
        import boto3
        s3 = boto3.client("s3")
        bucket, job = os.environ["BUCKET"], os.environ["JOB_ID"]
        stl = os.path.join(a.work, "body.stl")
        s3.download_file(bucket, f"inputs/{job}/body.stl", stl)
        out = os.path.join(a.work, "out")
    try:
        info = build_case(case, stl, params)
        run_case(case, info)
        collect(case, info, out)
    finally:
        if s3:
            # always upload logs so failures can be diagnosed from the web app
            os.makedirs(out, exist_ok=True)
            with zipfile.ZipFile(os.path.join(out, "logs.zip"), "w", zipfile.ZIP_DEFLATED) as z:
                for fn in os.listdir(case):
                    if fn.startswith("log."):
                        z.write(os.path.join(case, fn), fn)
            for fn in os.listdir(out):
                s3.upload_file(os.path.join(out, fn), bucket, f"outputs/{job}/{fn}")
    log("done")


if __name__ == "__main__":
    main()
